definitions:
  instance_mac_m2: &instance_mac_m2
    instance_type: mac_mini_m2
    max_build_duration: 120

  env_versions: &env_versions
    xcode: latest
    cocoapods: default

  app_environment: &app_environment
    groups:
      - appstore_credentials
    vars:
      BUNDLE_ID: "com.ajd.fghf76pjk1n"
      APP_STORE_APP_ID: "6759964881"
      XCODE_PROJECT: "NLS1.xcodeproj"
      XCODE_SCHEME: "App"
      XCODE_CONFIG: "Release-dev"

  ios_initialize_keychain: &ios_initialize_keychain
    name: Set up keychain
    script: |
      keychain initialize

  fetch_signing_files: &fetch_signing_files
    name: Fetch signing files
    script: |
      app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

  add_certs_to_keychain: &add_certs_to_keychain
    name: Add certificates to keychain
    script: |
      keychain add-certificates

  use_profiles: &use_profiles
    name: Apply provisioning profiles
    script: |
      xcode-project use-profiles

  increment_ios_build_number: &increment_ios_build_number
    name: Increment build number
    script: |
      #!/bin/sh
      set -ex
      cd "$FCI_BUILD_DIR"
      LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo 0)
      agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

  build_ipa: &build_ipa
    name: Build ipa
    script: |
      set -ex
      cd "$FCI_BUILD_DIR"
      xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME" --config "$XCODE_CONFIG"

workflows:
  ios-release:
    name: iOS release
    <<: *instance_mac_m2
    environment:
      <<: *env_versions
      <<: *app_environment
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - *ios_initialize_keychain
      - *fetch_signing_files
      - *add_certs_to_keychain
      - *use_profiles
      - *increment_ios_build_number
      - *build_ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  ios-staging:
    name: iOS staging
    <<: *instance_mac_m2
    environment:
      <<: *env_versions
      <<: *app_environment
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true
    scripts:
      - *ios_initialize_keychain
      - *fetch_signing_files
      - *add_certs_to_keychain
      - *use_profiles
      - *increment_ios_build_number
      - *build_ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
